export type PlayerColor = "black" | "white";
export type PointDto = { x: number; y: number };
export type MoveVertex = { point: PointDto } | "pass";
export type MoveDto = { color: PlayerColor; vertex: MoveVertex; move_number: number };
export type StoneDto = PointDto & { color: PlayerColor };
export type PositionDto = {
  board_size: number;
  move_number: number;
  to_play: PlayerColor;
  stones: StoneDto[];
  captures_black: number;
  captures_white: number;
  last_move?: MoveDto | null;
  errors: string[];
};
export type GameSummaryDto = { id: string; board_size: number; komi: number; black_name?: string | null; white_name?: string | null; result?: string | null; move_count: number };
export type GameDto = { summary: GameSummaryDto; moves: MoveDto[] };
export type SgfPropertyDto = { key: string; values: string[] };
export type SgfTreeNodeDto = {
  id: string;
  parent_id?: string | null;
  child_ids: string[];
  variation_index: number;
  depth: number;
  move_number?: number | null;
  color?: PlayerColor | null;
  vertex?: MoveVertex | null;
  name?: string | null;
  comment?: string | null;
  properties: SgfPropertyDto[];
  is_mainline: boolean;
};
export type SgfTreeDto = { root_id: string; nodes: SgfTreeNodeDto[] };
export type CandidateMoveDto = { vertex: MoveVertex; visits: number; winrate_black: number; score_mean_black: number; policy_prior?: number | null; pv: MoveVertex[] };
export type AnalysisFrameDto = { job_id: string; game_id?: string | null; node_id?: string | null; turn: number; visits: number; winrate_black: number; score_mean_black: number; score_stdev?: number | null; candidates: CandidateMoveDto[]; ownership?: number[] | null; policy?: number[] | null };
export type ProblemMarkerDto = { turn: number; severity: "info" | "inaccuracy" | "mistake" | "blunder"; winrate_loss: number; score_loss: number; label: string };
export type EngineBackendDto = "kata_go_analysis";
export type EngineProfileDto = { name: string; engine_path: string; model_path?: string | null; config_path?: string | null; working_dir?: string | null; backend: EngineBackendDto };
export type EngineProfileSettingsDto = { profile: EngineProfileDto; max_visits: number };
export type EngineProfileRecordDto = { id: string; profile: EngineProfileDto; max_visits: number };
export type EngineProfilesSettingsDto = { selected_profile_id: string; profiles: EngineProfileRecordDto[] };
export type AssetCheckDto = { path: string; exists: boolean; required: boolean; label: string };
export type AppHealthDto = { app: string; architecture: string; rust_backend_ready: boolean; notes: string[] };
export type KataGoLiveSmokeConfigDto = {
  profile?: EngineProfileDto | null;
  max_visits?: number | null;
  once_turn?: number | null;
  game_max_visits?: number | null;
  cancel_max_visits?: number | null;
  cancel_delay_ms?: number | null;
  run_game?: boolean | null;
  run_cancel?: boolean | null;
};
